name: Copile and push latex file
on:
  push:
    branches:
    - master
    paths:
      - 'latex/**'
  workflow_dispatch:

jobs:
  make_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: >
          echo '::set-output name=value::["visao_projeto", "modelagem_projeto" , "prova"]'
  clone_repo_and_install_dependencies:
    runs-on: ubuntu-latest
    needs: [make_matrix]
    strategy:
      matrix:
        value: ${{fromJson(needs.make_matrix.outputs.matrix)}}
    steps:
      - name: Install texlive dependencies
        run: >
              sudo apt-get update -y && 
              sudo apt install texlive -y &&
              sudo apt-get install texlive-latex-extra -y &&
              sudo apt-get install texlive-lang-portuguese -y
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Give permission
        run: 'sudo chmod -R 777 .'
      - name: Compile LaTeX document
        run: >
              cd ./latex/${{matrix.value}} &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main &&
              makeglossaries main &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main
        
      - name: Test if pdf was compiled
        run: >
              (cd ./latex/${{ matrix.value }} && test -f ./main.pdf && echo PDF exists) || 
              (echo PDF does not exist && pwd && ls && exit 1)      - name: Change filename and path of pdf
      - name: Change path of pdf
        run: >
              mv ./${{ matrix.value }}/main.pdf ./${{ matrix.value }}/${{ matrix.value }}.pdf &&
              cp	./latex/${{ matrix.value }}/${{ matrix.value }}.pdf	./
      - uses: EndBug/add-and-commit@v9
        with:
          message: Adding pdfs files
          default_author: github_actions