name: Copile and push latex file.
on:
  push:
    branches:
    - master
    paths:
      - 'latex/**'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Install latexmk
        run: 'sudo apt-get update -y && sudo apt-get install -y latexmk'
      - name: Clone repo
        run: 'git clone https://github.com/Rafasputnick/Gerenciamento-de-Tarefas.git'
      - name: Compile LaTeX document
        run: (cd ./Gerenciamento-de-Tarefas/latex && pwd && ls && latexmk -pdf -f -quiet main.tex)
      - name: Test if pdf was compiled
        run: '(cd ./Gerenciamento-de-Tarefas && test -f ./latex/main.pdf && echo PDF exists) || (echo PDF does not exist && pwd && ls ./latex/ && exit 1)'
      - name: Change filename and path of pdf
        run: 'cd ./Gerenciamento-de-Tarefas && cp	./latex/main.pdf	./ && mv ./main.pdf ./visao_projeto.pdf'
      - uses: EndBug/add-and-commit@v9
        with:
          message: Adding pdf file
          default_author: github_actions
          add: './visao_projeto.pdf'
