name: Copile and push latex file
on:
  push:
    branches:
    - master
    paths:
      - 'latex/**'
  workflow_dispatch:

jobs:
  compile_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Install texlive dependencies
        run: >
              sudo apt-get update -y && 
              sudo apt install texlive -y &&
              sudo apt-get install texlive-latex-extra -y &&
              sudo apt-get install texlive-lang-portuguese -y
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Give permission
        run: 'sudo chmod -R 777 .'
      - name: Compile LaTeX document vp
        run: >
              cd ./latex/visao_projeto &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main &&
              makeglossaries main &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main
      - name: Compile LaTeX document mp
        run: >
              cd ./latex/modelagem_projeto &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main &&
              makeglossaries main &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main
      - name: Compile LaTeX document p
        run: >
              cd ./latex/prova &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main &&
              makeglossaries main &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main &&
              pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main
                          
      - name: Test if pdf was compiled vp
        run: >
              (cd ./latex/visao_projeto && test -f ./main.pdf && echo PDF exists) || 
              (echo PDF does not exist && pwd && ls && exit 1)
      - name: Test if pdf was compiled mp
        run: >
              (cd ./latex/modelagem_projeto && test -f ./main.pdf && echo PDF exists) || 
              (echo PDF does not exist && pwd && ls && exit 1)
      - name: Test if pdf was compiled p
        run: >
              (cd ./latex/prova && test -f ./main.pdf && echo PDF exists) || 
              (echo PDF does not exist && pwd && ls && exit 1)      
      - name: Change path of pdf vp
        run: >
              mv ./latex/visao_projeto/main.pdf ./visao_projeto.pdf
      - name: Change path of pdf mp
        run: >
              mv ./latex/modelagem_projeto/main.pdf ./modelagem_projeto.pdf
      - name: Change path of pdf p
        run: >
              mv ./latex/prova/main.pdf ./prova.pdf
      - uses: EndBug/add-and-commit@v9
        with:
          message: Adding pdfs files
          default_author: github_actions
          add: './modelagem_projeto.pdf ./visao_projeto.pdf ./prova.pdf'